# Generated by Django 2.2.7 on 2019-11-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('date', models.TextField(verbose_name='Date')),
                ('author', models.TextField(verbose_name='Author')),
                ('channel', models.TextField(verbose_name='Channel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
            ],
        ),
    ]
