# Generated by Django 2.2.7 on 2019-12-19 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blockchat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nom Chatroom')),
                ('chatroom_admins', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Administrateurs de la chatroom')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nom Channel')),
                ('private', models.BooleanField(default=False, verbose_name='Conversation privée')),
                ('allowed_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Administrateurs de la chatroom')),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchat.Chatroom', verbose_name='Chatroom')),
            ],
        ),
    ]
