# Generated by Django 2.2.7 on 2019-12-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchat', '0002_auto_20191219_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom Channel'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom Chatroom'),
        ),
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.CharField(max_length=100, verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Message'),
        ),
    ]
