# Generated by Django 2.2.7 on 2019-12-19 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchat', '0003_auto_20191219_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='allowed_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs autorisés'),
        ),
    ]
