# Generated by Django 2.2.7 on 2019-12-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchat', '0004_auto_20191219_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchat.Channel', verbose_name='Channel'),
        ),
    ]
